resource "google_project_service" "services" {
  for_each = toset([
    "bigquery.googleapis.com",
    "dataform.googleapis.com",
  ])

  project            = var.project_id
  service            = each.value
  disable_on_destroy = false
}

resource "google_project_service_identity" "dataform" {
  provider = google-beta

  project = var.project_id
  service = "dataform.googleapis.com"

  depends_on = [google_project_service.services]
}

resource "google_bigquery_dataset" "workflow" {
  dataset_id                 = var.dataset_id
  friendly_name              = "Dataform SQL Workflow"
  description                = "Curated tables produced by the Dataform SQL workflow."
  location                   = var.location
  delete_contents_on_destroy = true

  depends_on = [google_project_service.services]
}

resource "google_bigquery_dataset" "assertions" {
  dataset_id                 = "${var.dataset_id}_assertions"
  friendly_name              = "Dataform SQL Workflow Assertions"
  description                = "Views generated by Dataform data quality assertions."
  location                   = var.location
  delete_contents_on_destroy = true

  depends_on = [google_project_service.services]
}

resource "google_dataform_repository" "workflow" {
  provider = google-beta

  name         = var.repository_id
  display_name = "SQL workflow portfolio project"
  region       = var.region

  depends_on = [google_project_service_identity.dataform]
}

resource "google_project_iam_member" "dataform_job_user" {
  project = var.project_id
  role    = "roles/bigquery.jobUser"
  member  = "serviceAccount:${google_project_service_identity.dataform.email}"
}

resource "google_bigquery_dataset_iam_member" "dataform_editor" {
  dataset_id = google_bigquery_dataset.workflow.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = "serviceAccount:${google_project_service_identity.dataform.email}"
}

resource "google_bigquery_dataset_iam_member" "dataform_assertions_editor" {
  dataset_id = google_bigquery_dataset.assertions.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = "serviceAccount:${google_project_service_identity.dataform.email}"
}